#!/bin/bash

cd
echo ""
echo "Сlick on allow to proceed"
termux-setup-storage & sleep 4 &>/dev/null
while true; do
if [ -e storage ]; then
rm -rf /sdcard/termux-box
break
else
echo "If you denied permission, change it manually in termux app settings now"
fi
sleep 1
done
mkdir -p /sdcard/termux-box
pkg clean
pkg update -y
pkg upgrade -y
sleep 2
echo ""
echo "Installing packages"
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install proot -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install tsu -y &>/dev/null
pkg install root-repo -y &>/dev/null
rm -rf $HOME/termux-box
mkdir -p $HOME/termux-box
cd $HOME/termux-box
wget https://github.com/olegos2/termux-box/raw/main/termux-x11-1.02.12-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.12-0-all.deb &>/dev/null
rm -rf termux-x11-1.02.12-0-all.deb

echo ""
echo "Copying preconfigured Rootfs..."
cd $HOME/termux-box
cp /sdcard/Download/rootfs.tar.xz .

echo ""
echo "Unzipping Rootfs"
tar -xf rootfs.tar.xz
rm -rf rootfs.tar.xz

cd $HOME/termux-box/ubuntu-fs/opt
cp /sdcard/Download/scripts.tar.gz . &>/dev/null
tar -xf scripts.tar.gz
rm -rf scripts.tar.gz

cd $HOME/termux-box/
cp /sdcard/Download/termux-box . &>/dev/null
chmod +x termux-box
mv termux-box $PREFIX/bin/
cp /sdcard/Download/start-proot.sh . &>/dev/null
cp /sdcard/Download/start-chroot.sh . &>/dev/null
chmod +x start-proot.sh
chmod +x start-chroot.sh

echo "Installing patch"

cd $HOME/termux-box/ubuntu-fs
cp /sdcard/Download/patch.tar.xz . &>/dev/null
rm -rf opt/d3d
rm -rf opt/mesa
tar -xf patch.tar.xz
rm -rf patch.tar.xz
cd
echo ""
echo "Done. Type 'termux-box' to start"

rm -rf "$0"
