#!/bin/bash

echo ""
echo "Сlick on allow to proceed"
termux-setup-storage & sleep 4 &>/dev/null
while true; do
if [ -e storage ]; then
rm -rf storage/shared/Box4Droid
break
else
echo "If you denied permission, change it manually in termux app settings now"
fi
sleep 1
done
mkdir -p storage/shared/Box4Droid
pkg update -y
sleep 2
echo ""
echo "Installing packages"
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install proot -y &>/dev/null
pkg install wget -y &>/dev/null
mkdir -p $HOME/Box4Droid
cd $HOME/Box4Droid
wget https://github.com/olegos2/termux-box/raw/main/termux-x11-1.02.07-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.07-0-all.deb &>/dev/null
rm -rf termux-x11-1.02.07-0-all.deb

echo ""
echo "Copying preconfigured Rootfs..."
cd $HOME/Box4Droid
cp $HOME/storage/shared/Download/rootfs.tar.xz $HOME/Box4Droid

echo ""
echo "Unzipping Rootfs"
tar -xf rootfs.tar.xz
rm -rf rootfs.tar.xz

cd $HOME/Box4Droid/ubuntu-fs/opt
wget https://github.com/olegos2/termux-box/raw/main/scripts.tar.gz &>/dev/null
tar -xf scripts.tar.gz
rm -rf scripts.tar.gz

cd $HOME/Box4Droid/
wget https://github.com/olegos2/termux-box/raw/main/box &>/dev/null
wget https://github.com/olegos2/termux-box/raw/main/start-ubuntu.sh &>/dev/null
chmod +x box
mv box $PREFIX/bin/
chmod +x start-ubuntu.sh

echo ""
echo "Done. Type 'box' to start"

rm -rf $HOME/install
