#!/bin/bash

cd $HOME/termux-box/ubuntu-fs/opt
wget https://github.com/olegos2/termux-box/raw/main/scripts.tar.gz &>/dev/null
mkdir tempscripts
tar -xf scripts.tar.gz -C tempscripts
rm -rf scripts.tar.gz
cd tempscripts
if [ ! -e ../cores.conf ]; then
mv cores.conf ..
fi
if [ ! -e ../fpscounter.conf ]; then
mv fpscounter.conf ..
mv fpscounterstate.conf ..
fi
rm -rf *.conf
mv * ..
cd ..
rm -rf tempscripts

cd $HOME/termux-box/
wget -N https://github.com/olegos2/termux-box/raw/main/termux-box &>/dev/null
chmod +x termux-box
mv termux-box $PREFIX/bin/
wget -N https://github.com/olegos2/termux-box/raw/main/start-proot.sh &>/dev/null
wget -N https://github.com/olegos2/termux-box/raw/main/start-chroot.sh &>/dev/null
chmod +x start-proot.sh
chmod +x start-chroot.sh

cd $HOME/termux-box/ubuntu-fs

wget -q --show-progress https://github.com/olegos2/termux-box/releases/download/0.0.1-alpha/patch.tar.xz
tar -xf patch.tar.xz
rm -rf patch.tar.xz

cd
echo ""
echo "After installing patch you should select \"update prefix after patch\" option in termux-box menu."

rm -rf "$0"
