#!/bin/bash

cd $HOME/termux-box/
wget -N https://github.com/olegos2/termux-box/raw/main/termux-box &>/dev/null
chmod +x termux-box
mv termux-box $PREFIX/bin/
wget -N https://github.com/olegos2/termux-box/raw/main/start-proot.sh &>/dev/null
wget -N https://github.com/olegos2/termux-box/raw/main/start-chroot.sh &>/dev/null
chmod +x start-proot.sh
chmod +x start-chroot.sh

cd $HOME/termux-box/ubuntu-fs

wget -q --show-progress https://github.com/olegos2/termux-box/releases/download/0.0.1-alpha/patch.tar.xz
tar -xf patch.tar.xz
rm -rf patch.tar.xz

cd

echo "After installing patch you should select \"update prefix after patch\" option in termux-box menu."
