#!/bin/bash

if [ ! -e ~/termux-box/update-timestamp ]; then
latestupdate=$(curl --connect-timeout 6 -s https://raw.githubusercontent.com/olegos2/termux-box/main/update-timestamp)
if [[ "$latestupdate" = "" ]]; then
echo "No internet connetion, try again"
return
fi
echo "$latestupdate">~/termux-box/update-timestamp
fi
current=$(date '+%s')
timestamp=$(cat ~/termux-box/update-timestamp)
seconds=$((current - timestamp))
minutes=$(((seconds / 60) % 60))
hours=$(((seconds / 3600) % 24))
days=$((seconds / 86400))
echo ""
echo -n "Installed patch released "
if [ $days = 1 ]; then echo -n "$days day, "
else echo -n "$days days, "; fi
if [ $hours = 1 ]; then echo -n "$hours hour, "
else echo -n "$hours hours, "; fi
if [ $minutes = 1 ]; then echo "$minutes minute ago"
else echo "$minutes minutes ago"; fi

sleep 0.5

latestupdate=$(curl --connect-timeout 6 -s https://raw.githubusercontent.com/olegos2/termux-box/main/update-timestamp)
if [[ "$latestupdate" = "" ]]; then
echo "Could not check for updates"
else
if [ "$timestamp" = "$latestupdate" ]; then
echo "termux-box is up to date!"
else
echo -n "A new patch is available! Do you want to install it? (Y/n) "
read sel
if [ "$sel" = "Y" ] || [ "$sel" = "y" ]; then
curl -s -o ~/y https://raw.githubusercontent.com/olegos2/termux-box/main/patch
chmod +x y
~/y
echo "$latestupdate">~/termux-box/update-timestamp
exec $PREFIX/bin/termux-box
else
echo "Update was not installed"
fi
fi
fi

sleep 0.5

cd $HOME/termux-box

sudo chown -hR $(whoami) ubuntu-fs/root $>/dev/null
touch ubuntu-fs/root/.hushlogin
mkdir -p /sdcard/Android/data/com.termux/files/Download &>/dev/null
termux-x11 :1 &>/dev/null &
rm -rf $PREFIX/tmp/pulse-*
pulseaudio -k >/dev/null 2>&1
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

mkdir /sdcard/termux-box >/dev/null 2>&1
cp -n ubuntu-fs/opt/Env.conf /sdcard/termux-box >/dev/null 2>&1
cp -n ubuntu-fs/opt/dxvk.conf /sdcard/termux-box >/dev/null 2>&1
negus=$(cat ubuntu-fs/opt/script.conf)
if [ "$negus" = "" ]; then
echo ""
echo "1) Proot"
echo "2) Chroot (root only)"
read oleg
elif [ "$negus" = "proot" ]; then
oleg=1
else
oleg=2
fi
case $oleg in
1)
echo "proot">ubuntu-fs/opt/script.conf
if [[ "$(sudo a)" = *"Are you rooted?"* ]]; then
 ./start-proot.sh
else
 echo "Warning! Using proot with root is unstable!"
 sleep 3
 sudo chown -hR root ubuntu-fs/root $>/dev/null
 sudo ./start-proot.sh
 sudo chown -hR $(whoami) ubuntu-fs/root $>/dev/null
fi
;;
2)
echo "chroot">ubuntu-fs/opt/script.conf
sudo chown -hR root ubuntu-fs/root $>/dev/null
sudo ./start-chroot.sh
sudo chown -hR $(whoami) ubuntu-fs/root $>/dev/null
;;
esac

pkill -f "app_process / com.termux.x11"
